name: In General Bug Report
description: Bug Report
title: "[Bug]: "
labels: ["bug", "triage"]
projects: []
assignees:
  - TheLegendarySpark
body:
  - type: dropdown
    id: location-of-the-bug
    attributes:
      label: Bug Location
      description: Where is this bug occuring?
      options:
        - Commands
        - User Interface
        - Shortcuts / Buttons / Command & Action Aliases
        - Global table (_G)
        - Player Remote Network (for sending data between players and server)
        - Cross Network (for sending data to all servers)
        - Cryptographic System / Encryption
        - Datastore
        - Policy Manager
        - Moderation
        - Vela
        - Queue / Signal
        - Server Assets (e.g. Jail box)
        - Core modules (e.g. Core, Datastore, Identity, Process, Remote, Moderation, & Logs)
        - Dependency modules (e.g. Filter, Network, Parser, Roles, & Utility)
        - Other
      default: 1
    validations:
      required: true


  - type: input
    id: frequency
    attributes:
      label: Frequency of the bug occurrence
      description: How frequently does this bug reproduce?
      placeholder: ex. every few minutes during gameplay / occasionally
    validations:
      required: true
      

  - type: dropdown
    id: version
    attributes:
      label: Version
      description: What version of Essential are you using? This is located inside your command panel.
      options:
        - 0.8.0 (Latest)
        - 0.7.X
        - 0.6.X
      default: 0
    validations:
      required: true
      
  - type: dropdown
    id: client-or-server
    attributes:
      label: In addition to the bug, is this bug reproducible in the server side or client side?
      multiple: false
      options:
        - Server-side (Happens in the server and has no effect on my OWN device)
        - Client (Happens in your OWN device while playing the game)
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduct
    attributes:
      label: How did you reproduce the bug?
      description: Tell us in a procedure of how you reproduced the bug. (1. I did this, 2. - I also did this, so and so on..)
      placeholder: |
          1. Triz blew up the server
          2. Players couldn't load their player data
          3. Essential no longer loaded for everyone until 5 minutes passed by
      value: |
          1. ...
          2. ..
          3. ..
          (Add more steps if you would like)
    validations:
      required: true
      
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: |
        Also tell us, what did you expect to happen?
        (Recommended) Additionally, you may provide visual presentation by uploading links (not shortened links), images, and videos.
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
